# Generated by Django 3.2.7 on 2021-09-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='default.jpg', upload_to='images/profile_photo', verbose_name='عکس پروفایل'),
        ),
    ]
