# Generated by Django 3.2.7 on 2021-09-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(max_length=280, null=True, verbose_name='بیوگرافی'),
        ),
    ]
