# Generated by Django 3.2.7 on 2021-10-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='images/default.jpg', upload_to='images/profile_photo', verbose_name='عکس پروفایل'),
        ),
    ]
