# Generated by Django 3.2.7 on 2021-09-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twit',
            options={'verbose_name': 'توییت', 'verbose_name_plural': 'توییت ها'},
        ),
    ]
