# Generated by Django 3.2.7 on 2021-09-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0002_alter_twit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='twit',
            field=models.TextField(max_length=280, verbose_name='توییت'),
        ),
    ]
