# Generated by Django 3.2.7 on 2021-09-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0003_alter_twit_twit'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='bio',
            field=models.TextField(max_length=280, null=True, verbose_name='بیو'),
        ),
    ]
