# Generated by Django 3.2.7 on 2021-09-30 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twit', '0005_remove_twit_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_twit', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
    ]
