# Generated by Django 3.2.7 on 2021-10-02 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0007_twit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 11, 8, 21, 59004, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
