# Generated by Django 3.2.7 on 2021-10-05 09:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0008_alter_twit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 9, 52, 38, 697479, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
