# Generated by Django 3.2.7 on 2021-10-06 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0009_alter_twit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
    ]
