# Generated by Django 3.2.7 on 2021-10-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0010_alter_twit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='img',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images'),
        ),
    ]
