# Generated by Django 3.2.7 on 2021-10-13 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twit', '0012_alter_twit_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='twit.twit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like_twits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
