# Generated by Django 3.2.7 on 2021-10-14 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twit', '0014_auto_20211013_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twit',
            name='likes',
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('twits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='twit.twit')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
